# Generated by Django 4.0.1 on 2023-02-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('soldBy', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='sellers',
            field=models.ManyToManyField(to='main_app.Seller'),
        ),
    ]
