# Generated by Django 4.0.1 on 2023-02-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_seller_record_sellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars'), ('GBP', 'British Pound Sterling')], default='EUR', max_length=3)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.record')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.seller')),
            ],
        ),
    ]
