# Generated by Django 4.0.1 on 2023-02-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_record_sellers_remove_seller_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sellers',
            field=models.ManyToManyField(through='main_app.Price', to='main_app.Seller'),
        ),
    ]
