# Generated by Django 4.0.1 on 2023-02-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_price_currency_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='soldBy',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
